// flow-typed signature: d495ecd5ef0666f091db61e7c899baf8
// flow-typed version: <<STUB>>/koa-etag_v^3.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-etag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-etag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-etag/index' {
  declare module.exports: $Exports<'koa-etag'>;
}
declare module 'koa-etag/index.js' {
  declare module.exports: $Exports<'koa-etag'>;
}
