// flow-typed signature: 160dcfe1e250c1a7b50170bc4cc6180c
// flow-typed version: <<STUB>>/rethinkdb_v^2.3.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rethinkdb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rethinkdb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rethinkdb/ast' {
  declare module.exports: any;
}

declare module 'rethinkdb/cursor' {
  declare module.exports: any;
}

declare module 'rethinkdb/errors' {
  declare module.exports: any;
}

declare module 'rethinkdb/net' {
  declare module.exports: any;
}

declare module 'rethinkdb/proto-def' {
  declare module.exports: any;
}

declare module 'rethinkdb/rethinkdb' {
  declare module.exports: any;
}

declare module 'rethinkdb/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rethinkdb/ast.js' {
  declare module.exports: $Exports<'rethinkdb/ast'>;
}
declare module 'rethinkdb/cursor.js' {
  declare module.exports: $Exports<'rethinkdb/cursor'>;
}
declare module 'rethinkdb/errors.js' {
  declare module.exports: $Exports<'rethinkdb/errors'>;
}
declare module 'rethinkdb/net.js' {
  declare module.exports: $Exports<'rethinkdb/net'>;
}
declare module 'rethinkdb/proto-def.js' {
  declare module.exports: $Exports<'rethinkdb/proto-def'>;
}
declare module 'rethinkdb/rethinkdb.js' {
  declare module.exports: $Exports<'rethinkdb/rethinkdb'>;
}
declare module 'rethinkdb/util.js' {
  declare module.exports: $Exports<'rethinkdb/util'>;
}
