sudo: required
language: node_js
node_js:
  - 10
services:
  - docker
cache:
  directories:
    - /home/travis/budde377/thang/packages/app/node_modules/
    - /home/travis/budde377/thang/packages/api/node_modules/
before_install:
  - sudo ./scripts/install.sh
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
  - npm i -g npm@latest
  - npm ci
  - docker-compose -f docker-compose.test.yaml up -d

install:
  - lerna bootstrap --ci

script:
  - lerna run test

deploy:
  provider: script
  skip_cleanup: true
  script: ./scripts/deploy.sh
  on:
    branch: master
