sudo: required
language: node_js
node_js:
  - 9
services:
  - docker

before_install:
  - sudo ./scripts/install.sh
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
  - npm i -g npm@latest
  - npm ci
  - docker-compose up -d rdb

install:
  - npm run ci

script:
  - npm test

deploy:
  provider: script
  skip_cleanup: true
  script: ./scripts/deploy.sh
  on:
    branch: master
