sudo: required
language: node_js
node_js:
  - 9
services:
  - docker

before_install:
  - npm i -g npm@latest
  - npm ci

install:
  - npm run ci

script:
  - npm test

deploy:
  provider: script
  skip_cleanup: true
  script: ./scripts/deploy.sh
  on:
    branch: master
