version: '3'
services:
  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
    command: --smallfiles --replSet trs0
    volumes:
      - ./docker/initTestDb.js:/docker-entrypoint-initdb.d/initDb.js
