
rethink:
  host: 'RETHINK_HOST'

port:
  __name: PORT
  __format: "json"

version: VERSION

auth:
  management:
    clientId: AUTH_MANAGEMENT_CLIENT_ID
    clientSecret: AUTH_MANAGEMENT_CLIENT_SECRET

mongo:
  url: MONGO_URL
