port: 3000

mongo:
  url: mongodb://localhost:27017/?replicaSet=rs0
  replicaSet: rs0
auth:
  verify:
    algorithms:
      - RS256
    audience: https://api.thang.io/
    issuer: https://thang.eu.auth0.com/
  jwks:
    strictSsl: true
    jwksUri: https://thang.eu.auth0.com/.well-known/jwks.json
  userInfoUrl: https://thang.eu.auth0.com/userinfo
  management:
    audience: https://thang.eu.auth0.com/api/v2/
    domain: thang.eu.auth0.com
    clientId: id
    clientSecret: secret
  cache:
    max: 3000

defaultTimezone: Europe/Copenhagen

url:
  http: http://localhost:3000

version: latest
