port: 3000

rethink:
  db: thang
  host: localhost

auth:
  verify:
    algorithms:
      - RS256
    audience: https://api.thang.io/
    issuer: https://thang.eu.auth0.com/
  jwks:
    strictSsl: true
    jwksUri: https://thang.eu.auth0.com/.well-known/jwks.json
  userInfoUrl: https://thang.eu.auth0.com/userinfo
  cache:
    max: 3000

defaultTimezone: Europe/Copenhagen

url:
  http: http://localhost:3000

version: latest
