apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
data:
    serverKey: {{ .Values.server.key | b64enc | quote }}
    authClientSecret: {{ .Values.auth.clientSecret | b64enc | quote }}
type: Opaque
