port:
  __name: PORT
  __format: "json"
host: HOST

api:
  client:
    http: API_CLIENT_HTTP
    ws: API_CLIENT_WS
  server:
    http: API_SERVER_HTTP
    ws: API_SERVER_WS

version: VERSION

server:
  key: SERVER_KEY

auth:
  clientSecret: AUTH_CLIENT_SECRET

redis:
  host: REDIS_HOST
