port: 3000
host: localhost
auth:
  domain: thang.eu.auth0.com
  clientId: FgMrWfrKPBoiqOiWK0v5sUCH9j8dtXkA
  cleintSecret: FOOBAR
  redirectUri: http://localhost:4001/auth/callback
  audience: https://api.thang.io/
  responseType: token id_token
  scope: openid email profile

api:
  client:
    http: http://localhost:3000
    ws: ws://localhost:3000
  server:
    http: http://localhost:3000
    ws: ws://localhost:3000

version: latest

session:
  key: thang-sesh
  rolling: true
  maxAge: 86400000

server:
  key: foobar

redis:
  host: localhost
  port: 6379
