port: 3000
host: localhost
auth:
  domain: thang.eu.auth0.com
  clientID: FgMrWfrKPBoiqOiWK0v5sUCH9j8dtXkA
  redirectUri: http://localhost:4000/popup/callback
  audience: https://api.thang.io/
  responseType: token id_token
  scope: openid email profile

api:
  client:
    http: http://localhost:3000
    ws: ws://localhost:3000
  server:
    http: http://api:3000
    ws: ws://api:3000

version: latest
